### ISSUE TITLE
problem running on python 3.8.5

### ISSUE THREAD

**Issue by kobygold** [csmailis/NPYViewer#3]
Hi,
I tried running on python 3.8.5, and installed the requirements with 'pip install -r requirements.txt', but I get this error message when trying to run:
```
Traceback (most recent call last):
  File "NPYViewer.py", line 2, in <module>
    from PyQt5.QtWidgets import *
ModuleNotFoundError: No module named 'PyQt5'

```
I see that PyQt5 is not listed under the requirements.txt file...
Which version of PyQt5 do I need to install?
Shouldn't it be listed in the requirements.txt file...?

**Comment by simon-h03** [comment]
PyQt5 version 5.12.3 does not exist, try a newer version like 5.13 or just use `pip3 install PyQt5`, latest version seems fine.
