### ISSUE TITLE
custom dtypes

### ISSUE THREAD

**Issue by mrudorfer** [csmailis/NPYViewer#4]
Hi,
First of all, thanks a lot for your work, this is a really helpful tool to work with npy files!
Now to my issue ;-)
I have a npy file that holds an array with custom dtype, e.g. something like:
```
my_array = np.empty(20, dtype=[('name', 'S32'), ('value', '<f8')])
my_array['value'] = np.arange(20)
np.save('tmp.npy', my_array)
```

Trying to load this results into it being treated as 1d-array, where the column contains both names and values.

Do you plan to support such custom dtypes as individual columns as well? Or could you comment on what changes would be required to do so (I could potentially contribute)?

Thanks!

**Comment by csmailis** [comment]
Custom data types are currently not supported.
The only supported data format is 2D lists of datatypes that can be converted to strings.

Although this is an important constraint for NPYViewer, I intended to keep the program as simple and naive as possible at the current stage .

I will possibly provide support for custom data types in the future, but I do not have a specific timeframe.

Changes should be made in the "OpenNPY()" function to support custom data types. Also, it would be good to introduce extra widgets to allow viewing lists within lists, etc.
Additional modifications should take place for the plotting widgets (e.g., view 3D pointcloud), so as to be able to handle custom datatypes.

Feel free to contribute if you have the time.
